<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icons\Glystrata.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Glystrata.Core\Glystrata.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\Glystrata.ico" />
    <Resource Include="Resources\Icons\SnapshotFile.ico" />
    <Resource Include="Resources\Icons\**\*.png" />
    <Resource Include="Resources\Emoji\twemoji-72.zip" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE" Link="LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\THIRD-PARTY-NOTICES.txt" Link="THIRD-PARTY-NOTICES.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\licenses\DOTNET-THIRD-PARTY-NOTICES.txt" Link="DOTNET-THIRD-PARTY-NOTICES.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\licenses\TWEMOJI-LICENSE-GRAPHICS.txt" Link="TWEMOJI-LICENSE-GRAPHICS.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
