global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Controls.Primitives;
global using System.Windows.Data;
global using System.Windows.Documents;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using System.Windows.Threading;
global using Application = System.Windows.Application;
global using Brush = System.Windows.Media.Brush;
global using Brushes = System.Windows.Media.Brushes;
global using Button = System.Windows.Controls.Button;
global using Color = System.Windows.Media.Color;
global using ComboBox = System.Windows.Controls.ComboBox;
global using ContextMenu = System.Windows.Controls.ContextMenu;
global using FontFamily = System.Windows.Media.FontFamily;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using Image = System.Windows.Controls.Image;
global using Key = System.Windows.Input.Key;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using Keyboard = System.Windows.Input.Keyboard;
global using Menu = System.Windows.Controls.Menu;
global using MenuItem = System.Windows.Controls.MenuItem;
global using MessageBox = System.Windows.MessageBox;
global using ModifierKeys = System.Windows.Input.ModifierKeys;
global using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
global using Orientation = System.Windows.Controls.Orientation;
global using Panel = System.Windows.Controls.Panel;
global using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
global using StatusBar = System.Windows.Controls.Primitives.StatusBar;
global using TabControl = System.Windows.Controls.TabControl;
global using TextBox = System.Windows.Controls.TextBox;
global using ToolBar = System.Windows.Controls.ToolBar;
global using TreeView = System.Windows.Controls.TreeView;
global using VerticalAlignment = System.Windows.VerticalAlignment;
global using Group = MDeditor.Core.Groups.Group;
global using GroupItem = MDeditor.Core.Groups.GroupItem;
global using MDeditor.Core.Documents;
global using MDeditor.Core.Groups;
global using MDeditor.Core.Layout;
global using MDeditor.Core.Markdown;
global using MDeditor.Core.Persistence;
global using MDeditor.Core.Snapshots;
global using MDeditor.Dialogs;
global using MDeditor.Services;
